server:
  port: 8001

spring:
  application:
    name: service-center

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false			# 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 5000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/