server:
  port: 8080

spring:
  application:
    name: atomikos-test

jdbc:
  ds:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.107.97.132:3306/web?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=true
    username: root
    password: root
  ds1:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.107.97.132:3306/resource?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=true
    username: root
    password: root


